#!/bin/bash
# Vercel environment variable setup script
# Usage: ./vercel-env-setup.sh

echo "================================"
echo "Vercel Environment Variable Setup Guide"
echo "================================"
echo ""
echo "Please configure the following environment variables in the Vercel Dashboard:"
echo ""
echo "1. Sign in to Vercel: https://vercel.com"
echo "2. Select your project"
echo "3. Open Settings -> Environment Variables"
echo "4. Add the variables below:"
echo ""
echo "-----------------------------------"
echo "Critical configuration (required):"
echo "-----------------------------------"
echo "DATABASE_PROVIDER=supabase"
echo ""
echo "-----------------------------------"
echo "Supabase configuration (required):"
echo "-----------------------------------"
echo "NEXT_PUBLIC_SUPABASE_URL=https://your-project.supabase.co"
echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=your-anon-key"
echo "SUPABASE_SERVICE_ROLE_KEY=your-service-role-key"
echo ""
echo "* How to retrieve Supabase keys:"
echo "   https://supabase.com/dashboard/project/YOUR_PROJECT/settings/api"
echo ""
echo "-----------------------------------"
echo "Google OAuth (optional):"
echo "-----------------------------------"
echo "NEXT_PUBLIC_GOOGLE_CLIENT_ID=your-client-id.apps.googleusercontent.com"
echo "GOOGLE_CLIENT_ID=your-client-id.apps.googleusercontent.com"
echo "GOOGLE_CLIENT_SECRET=your-client-secret"
echo ""
echo "================================"
echo "Important notes:"
echo "================================"
echo "1. Mark SUPABASE_SERVICE_ROLE_KEY and GOOGLE_CLIENT_SECRET as 'Sensitive'"
echo "2. Add each variable to both Production and Preview environments"
echo "3. After adding everything, click 'Redeploy' to redeploy the project"
echo ""
echo "================================"
echo "Database migrations:"
echo "================================"
echo "Run the following in the Supabase Dashboard SQL Editor:"
echo "1. supabase/migrations/0001_init.sql"
echo "2. supabase/migrations/0002_google_oauth.sql"
echo "3. supabase/migrations/0003_hero_slides.sql"
echo ""
