#!/bin/bash
# Vercel 环境变量设置脚本
# 使用方法：./vercel-env-setup.sh

echo "================================"
echo "Vercel 环境变量设置指南"
echo "================================"
echo ""
echo "请在 Vercel Dashboard 中设置以下环境变量："
echo ""
echo "1. 登录 Vercel: https://vercel.com"
echo "2. 选择您的项目"
echo "3. 进入 Settings → Environment Variables"
echo "4. 添加以下变量："
echo ""
echo "-----------------------------------"
echo "关键配置（必需）:"
echo "-----------------------------------"
echo "DATABASE_PROVIDER=supabase"
echo ""
echo "-----------------------------------"
echo "Supabase 配置（必需）:"
echo "-----------------------------------"
echo "NEXT_PUBLIC_SUPABASE_URL=https://your-project.supabase.co"
echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=your-anon-key"
echo "SUPABASE_SERVICE_ROLE_KEY=your-service-role-key"
echo ""
echo "📌 获取 Supabase 密钥："
echo "   https://supabase.com/dashboard/project/YOUR_PROJECT/settings/api"
echo ""
echo "-----------------------------------"
echo "Google OAuth（可选）:"
echo "-----------------------------------"
echo "NEXT_PUBLIC_GOOGLE_CLIENT_ID=your-client-id.apps.googleusercontent.com"
echo "GOOGLE_CLIENT_ID=your-client-id.apps.googleusercontent.com"
echo "GOOGLE_CLIENT_SECRET=your-client-secret"
echo ""
echo "================================"
echo "重要提示："
echo "================================"
echo "1. SUPABASE_SERVICE_ROLE_KEY 和 GOOGLE_CLIENT_SECRET 要标记为 'Sensitive'"
echo "2. 所有变量都要同时添加到 Production 和 Preview 环境"
echo "3. 添加完成后，点击 'Redeploy' 重新部署项目"
echo ""
echo "================================"
echo "数据库迁移："
echo "================================"
echo "在 Supabase Dashboard 的 SQL Editor 中依次运行："
echo "1. supabase/migrations/0001_init.sql"
echo "2. supabase/migrations/0002_google_oauth.sql"
echo "3. supabase/migrations/0003_hero_slides.sql"
echo ""

